class User(object):
    """
    User encapsulates a User ID generated by Google Firebase, an EID, and an Email
    """

    def __init__(self, uid, eid, email, lot=None):
        """
        Construct a new 'USER' Object.

        :param uid: The id reference from Firebase.
        :param eid: The EID of the student (Student ID).
        :param email: The email of the student that is used for their log in.
        :param lot: The lot that the user is using.
        :return: returns nothing
        """

        self.uid = uid
        self.eid = eid
        self.email = email
        self.lot = lot

    def updateLot(self, lot):
        """
        Update the lot the user is currently using.

        :param lot: The lot the user is currently using.
        :return: returns nothing
        """

        self.lot = lot




